version: '3.7'

# general way of making services:
# <service-name>:
  # image: <image-name>
  # ports:
    # - <ext-port>:<int-port>
  # environment:
    # <env-name>: <value-or-env-file-name>
  # env_file: <path-to-env-file>
  # command: [<comma-separated-values-of-starting-it-up>] 
  # volumes:
    # <ref-volume>:<container-volume>

services:
  goose-counter:
    image: ehuan2/htngc-goose-counter:latest
    ports:
      - 8080:8080
    environment: 
      PYTHONUNBUFFERED: 1
    command: ["python", "main.py"]

  frontend:
    image: ehuan2/htngc-frontend:latest
    ports:
      - 80:80
    command: ["npm", "start"]
    env_file: ./conf/.env-frontend

  nickname-generator:
    image: ehuan2/htngc-nickname-generator:latest
    ports:
      - 8081
    command: ["racket", "main.rkt"]

  redis:
    image: redis:latest
    ports:
      - 6379
    volumes:
      - redis-data:/redis-data

volumes:
  redis-data: