version: '3.7'

services:
  goose-counter:
    image: ehuan2/htngc-goose-counter:latest
    ports:
      - 8080:8080
    environment: 
      PYTHONUNBUFFERED: 1
    command: ["python", "main.py"]

  frontend:
    image: ehuan2/htngc-frontend:latest
    ports:
      - 80:80
    command: ["npm", "start"]
    env_file: ./conf/.env-frontend

  nickname-generator:
    image: ehuan2/htngc-nickname-generator:latest
    ports:
      - 8081
    command: ["racket", "main.rkt"]

  redis:
    image: redis:latest
    ports:
      - 6379
    volumes:
      - redis-data:/redis-data

volumes:
  redis-data: